# Generated by Django 5.0.6 on 2024-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
    ]
