# Generated by Django 5.0.6 on 2024-06-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutsugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='suggestion',
            field=models.CharField(max_length=750),
        ),
    ]
